version: "3.3"

services:

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388/tcp" # <-- change me (if you want)
      - "8388:8388/udp" # <-- change me(if you want)
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt # <-- change me
    restart: always

  watchtower: # (optional) auto-update when new version released
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    restart: unless-stopped
